import { defineConfig, type DummyRuleMap } from "oxlint";

export const rules = {
  "eslint/array-callback-return": [
    "error",
    {
      allowImplicit: true,
      checkForEach: false,
      allowVoid: true,
    },
  ],
  "eslint/arrow-body-style": [
    "error",
    "as-needed",
    {
      requireReturnForObjectLiteral: false,
    },
  ],
  "eslint/block-scoped-var": ["error"],
  curly: ["error", "all"],
  "eslint/constructor-super": ["error"],
  "eslint/default-case": [
    "error",
    {
      commentPattern: "^no default$",
    },
  ],
  "eslint/default-case-last": ["error"],
  "eslint/default-param-last": ["error"],
  eqeqeq: ["error", "always"],
  "eslint/for-direction": ["error"],
  "eslint/func-names": ["warn", "as-needed"],
  "eslint/getter-return": ["error"],
  "eslint/grouped-accessor-pairs": [
    "error",
    "getBeforeSet",
    {
      enforceForTSTypes: true,
    },
  ],
  "eslint/guard-for-in": ["error"],
  "eslint/new-cap": [
    "error",
    {
      newIsCap: true,
      capIsNew: false,
      properties: true,
    },
  ],
  "eslint/no-alert": ["warn"],
  "eslint/no-array-constructor": ["error"],
  "eslint/no-async-promise-executor": ["error"],
  "eslint/no-await-in-loop": ["error"],
  "eslint/no-bitwise": ["error"],
  "eslint/no-caller": ["error"],
  "eslint/no-case-declarations": ["error"],
  "eslint/no-class-assign": ["error"],
  "eslint/no-compare-neg-zero": ["error"],
  "eslint/no-cond-assign": ["error", "except-parens"],
  "eslint/no-console": ["warn"],
  "eslint/no-const-assign": ["error"],
  "eslint/no-constant-binary-expression": ["error"],
  "eslint/no-constant-condition": ["error"],
  "eslint/no-constructor-return": ["error"],
  "eslint/no-continue": ["error"],
  "eslint/no-control-regex": ["error"],
  "eslint/no-debugger": ["error"],
  "eslint/no-delete-var": ["error"],
  "eslint/no-dupe-class-members": ["error"],
  "eslint/no-dupe-else-if": ["error"],
  "eslint/no-dupe-keys": ["error"],
  "eslint/no-duplicate-case": ["error"],
  "eslint/no-else-return": [
    "error",
    {
      allowElseIf: false,
    },
  ],
  "eslint/no-empty": [
    "error",
    {
      allowEmptyCatch: true,
    },
  ],
  "eslint/no-empty-character-class": ["error"],
  "eslint/no-empty-function": ["error"],
  "eslint/no-empty-pattern": ["error"],
  "eslint/no-eval": ["error"],
  "eslint/no-empty-static-block": ["error"],
  "eslint/no-ex-assign": ["error"],
  "eslint/no-extend-native": ["error"],
  "eslint/no-extra-bind": ["error"],
  "eslint/no-extra-boolean-cast": ["error"],
  "eslint/no-extra-label": ["error"],
  "eslint/no-fallthrough": ["error"],
  "eslint/no-func-assign": ["error"],
  "eslint/no-global-assign": ["error"],
  "eslint/no-import-assign": ["error"],
  "eslint/no-inner-declarations": ["error"],
  "eslint/no-invalid-regexp": ["error"],
  "eslint/no-irregular-whitespace": ["error"],
  "eslint/no-iterator": ["error"],
  "eslint/no-label-var": ["error"],
  "eslint/no-labels": ["error"],
  "eslint/no-lone-blocks": ["error"],
  "eslint/no-lonely-if": ["error"],
  "eslint/no-loop-func": ["error"],
  "eslint/no-loss-of-precision": ["error"],
  "eslint/no-misleading-character-class": ["error"],
  "eslint/no-multi-assign": ["error"],
  "eslint/no-multi-str": ["error"],
  "eslint/no-new": ["error"],
  "eslint/no-new-func": ["error"],
  "eslint/no-new-native-nonconstructor": ["error"],
  "eslint/no-new-wrappers": ["error"],
  "eslint/no-nonoctal-decimal-escape": ["error"],
  "eslint/no-obj-calls": ["error"],
  "eslint/no-object-constructor": ["error"],
  "eslint/no-param-reassign": [
    "error",
    {
      ignorePropertyModificationsFor: [
        "ctx",
        "context",
        "req",
        "request",
        "res",
        "response",
      ],
      props: true,
    },
  ],
  "eslint/no-plusplus": ["error"],
  "eslint/no-promise-executor-return": ["error"],
  "eslint/no-proto": ["error"],
  "eslint/no-prototype-builtins": ["error"],
  "eslint/no-redeclare": ["error"],
  "eslint/no-regex-spaces": ["error"],
  "eslint/no-restricted-globals": [
    "error",
    {
      restrictedGlobals: Object.fromEntries(
        [
          // Number globals
          ["isFinite", "isNaN"].map((name) => [
            name,
            `Use Number.${name} instead.`,
          ]),
          // window globals
          [
            "addEventListener",
            "blur",
            "close",
            "closed",
            "confirm",
            "defaultStatus",
            "defaultstatus",
            "event",
            "external",
            "find",
            "focus",
            "frameElement",
            "frames",
            "history",
            "innerHeight",
            "innerWidth",
            "length",
            "location",
            "locationbar",
            "menubar",
            "moveBy",
            "moveTo",
            "name",
            "onblur",
            "onerror",
            "onfocus",
            "onload",
            "onresize",
            "onunload",
            "open",
            "opener",
            "opera",
            "outerHeight",
            "outerWidth",
            "pageXOffset",
            "pageYOffset",
            "parent",
            "print",
            "removeEventListener",
            "resizeBy",
            "resizeTo",
            "screen",
            "screenLeft",
            "screenTop",
            "screenX",
            "screenY",
            "scroll",
            "scrollbars",
            "scrollBy",
            "scrollTo",
            "scrollX",
            "scrollY",
            "self",
            "status",
            "statusbar",
            "stop",
            "toolbar",
            "top",
          ].map((name) => [name, `Use window.${name} instead.`]),
        ].flat(),
      ),
    },
  ],
  "eslint/no-return-assign": ["error", "always"],
  "eslint/no-script-url": ["error"],
  "eslint/no-self-assign": [
    "error",
    {
      props: true,
    },
  ],
  "eslint/no-self-compare": ["error"],
  "eslint/no-sequences": ["error"],
  "eslint/no-setter-return": ["error"],
  "eslint/no-shadow": ["error"],
  "eslint/no-shadow-restricted-names": [
    "error",
    {
      reportGlobalThis: true,
    },
  ],
  "eslint/no-sparse-arrays": ["error"],
  "eslint/no-template-curly-in-string": ["error"],
  "eslint/no-this-before-super": ["error"],
  "eslint/no-throw-literal": ["error"],
  "eslint/no-unassigned-vars": ["error"],
  "eslint/no-undef": ["error"],
  "eslint/no-unneeded-ternary": [
    "error",
    {
      defaultAssignment: false,
    },
  ],
  "eslint/no-unexpected-multiline": ["error"],
  "eslint/no-unreachable": ["error"],
  "eslint/no-unsafe-finally": ["error"],
  "eslint/no-unsafe-negation": ["error"],
  "eslint/no-unsafe-optional-chaining": [
    "error",
    {
      disallowArithmeticOperators: true,
    },
  ],
  "eslint/no-unused-expressions": [
    "error",
    {
      allowShortCircuit: true,
      allowTernary: true,
      allowTaggedTemplates: true,
      enforceForJSX: true,
    },
  ],
  "eslint/no-unused-labels": ["error"],
  "eslint/no-unused-vars": [
    "warn",
    {
      vars: "all",
      varsIgnorePattern: /^_/.source,
      args: "after-used",
      argsIgnorePattern: /^_/.source,
      caughtErrors: "all",
      caughtErrorsIgnorePattern: /^_/.source,
      destructuredArrayIgnorePattern: /^_/.source,
      ignoreRestSiblings: true,
    },
  ],
  "eslint/no-unused-private-class-members": ["error"],
  "eslint/no-useless-backreference": ["error"],
  "eslint/no-useless-catch": ["error"],
  "eslint/no-useless-computed-key": ["error"],
  "eslint/no-useless-concat": ["error"],
  "eslint/no-useless-constructor": ["error"],
  "eslint/no-useless-escape": ["error"],
  "eslint/no-useless-rename": ["error"],
  "eslint/no-useless-return": ["error"],
  "eslint/no-var": ["error"],
  "eslint/no-with": ["error"],
  "eslint/operator-assignment": ["error", "always"],
  "eslint/prefer-const": [
    "error",
    {
      destructuring: "any",
      ignoreReadBeforeAssign: true,
    },
  ],
  "eslint/prefer-destructuring": [
    "error",
    {
      AssignmentExpression: {
        array: true,
        object: false,
      },
      VariableDeclarator: {
        array: false,
        object: true,
      },
    },
    {
      enforceForRenamedProperties: false,
    },
  ],
  "eslint/prefer-exponentiation-operator": ["error"],
  "eslint/prefer-numeric-literals": ["error"],
  "eslint/prefer-object-spread": ["error"],
  "eslint/prefer-promise-reject-errors": ["error"],
  "eslint/prefer-rest-params": ["error"],
  "eslint/prefer-spread": ["error"],
  "eslint/prefer-template": ["error"],
  "eslint/preserve-caught-error": ["error"],
  radix: ["error"],
  "eslint/require-await": ["error"],
  "eslint/require-yield": ["error"],
  "eslint/symbol-description": ["error"],
  "eslint/unicode-bom": ["error", "never"],
  "eslint/use-isnan": ["error"],
  "eslint/valid-typeof": [
    "error",
    {
      requireStringLiterals: true,
    },
  ],
  "eslint/vars-on-top": ["error"],
  yoda: ["error"],
  "eslint/prefer-object-has-own": ["error"],
} as const satisfies DummyRuleMap;

export const config = defineConfig({
  plugins: ["eslint"],
  rules,
});

export default config;
