import type { OxlintRule } from "../common.ts";

const JS_RULES = [
  {
    scope: "eslint_js",
    value: "no-restricted-exports",
    category: "restriction",
    type_aware: false,
    fix: "none",
    default: false,
    docs_url: "https://eslint.org/docs/latest/rules/no-restricted-exports",
    plugin: "eslint-js",
    name: "eslint-js/no-restricted-exports",
    isBuiltIn: false,
    isCompatible: false,
  },
  {
    scope: "eslint_js",
    value: "no-restricted-syntax",
    category: "restriction",
    type_aware: false,
    fix: "none",
    default: false,
    docs_url: "https://eslint.org/docs/latest/rules/no-restricted-syntax",
    plugin: "eslint-js",
    name: "eslint-js/no-restricted-syntax",
    isBuiltIn: false,
    isCompatible: false,
  },
  {
    scope: "eslint_js",
    value: "no-unreachable-loop",
    category: "correctness",
    type_aware: false,
    fix: "none",
    default: false,
    docs_url: "https://eslint.org/docs/latest/rules/no-unreachable-loop",
    plugin: "eslint-js",
    name: "eslint-js/no-unreachable-loop",
    isBuiltIn: false,
    isCompatible: false,
  },
  {
    scope: "eslint_js",
    value: "no-useless-assignment",
    category: "correctness",
    type_aware: false,
    fix: "none",
    default: false,
    docs_url: "https://eslint.org/docs/latest/rules/no-useless-assignment",
    plugin: "eslint-js",
    name: "eslint-js/no-useless-assignment",
    isBuiltIn: false,
    isCompatible: false,
  },
  {
    scope: "eslint_js",
    value: "object-shorthand",
    category: "style",
    type_aware: false,
    fix: "fixable_fix",
    default: false,
    docs_url: "https://eslint.org/docs/latest/rules/object-shorthand",
    plugin: "eslint-js",
    name: "eslint-js/object-shorthand",
    isBuiltIn: false,
    isCompatible: false,
  },
  {
    scope: "eslint_js",
    value: "one-var",
    category: "style",
    type_aware: false,
    fix: "fixable_fix",
    default: false,
    docs_url: "https://eslint.org/docs/latest/rules/one-var",
    plugin: "eslint-js",
    name: "eslint-js/one-var",
    isBuiltIn: false,
    isCompatible: false,
  },
  {
    scope: "eslint_js",
    value: "prefer-arrow-callback",
    category: "style",
    type_aware: false,
    fix: "fixable_fix",
    default: false,
    docs_url: "https://eslint.org/docs/latest/rules/prefer-arrow-callback",
    plugin: "eslint-js",
    name: "eslint-js/prefer-arrow-callback",
    isBuiltIn: false,
    isCompatible: false,
  },
] as const satisfies OxlintRule[];

export const getJsRules = (): OxlintRule[] => [...JS_RULES];
