import type { DummyRuleMap, OxlintConfig } from "oxlint";

export const rules = {
  "unicorn/catch-error-name": ["error"],
  "unicorn/consistent-date-clone": ["error"],
  "unicorn/consistent-empty-array-spread": ["error"],
  "unicorn/consistent-existence-index-check": ["error"],
  "unicorn/custom-error-definition": ["error"],
  "unicorn/error-message": ["error"],
  "unicorn/escape-case": ["error"],
  "unicorn/filename-case": ["error"],
  "unicorn/no-abusive-eslint-disable": ["error"],
  "unicorn/no-anonymous-default-export": ["error"],
  "unicorn/no-array-method-this-argument": ["error"],
  "unicorn/no-array-reverse": ["error"],
  "unicorn/no-array-sort": ["error"],
  "unicorn/no-await-in-promise-methods": ["error"],
  "unicorn/no-console-spaces": ["error"],
  "unicorn/no-document-cookie": ["error"],
  "unicorn/no-empty-file": ["error"],
  "unicorn/no-hex-escape": ["error"],
  "unicorn/no-immediate-mutation": ["error"],
  "unicorn/no-instanceof-array": ["error"],
  "unicorn/no-invalid-fetch-options": ["error"],
  "unicorn/no-invalid-remove-event-listener": ["error"],
  "unicorn/no-length-as-slice-end": ["error"],
  "unicorn/no-lonely-if": ["error"],
  "unicorn/no-negation-in-equality-check": ["error"],
  "unicorn/no-new-array": ["error"],
  "unicorn/no-single-promise-in-promise-methods": ["error"],
  "unicorn/no-thenable": ["error"],
  "unicorn/no-this-assignment": ["error"],
  "unicorn/no-typeof-undefined": [
    "error",
    {
      checkGlobalVariables: true,
    },
  ],
  "unicorn/no-unnecessary-array-flat-depth": ["error"],
  "unicorn/no-unnecessary-array-splice-count": ["error"],
  "unicorn/no-unnecessary-await": ["error"],
  "unicorn/no-unnecessary-slice-end": ["error"],
  "unicorn/no-useless-collection-argument": ["error"],
  "unicorn/no-useless-error-capture-stack-trace": ["error"],
  "unicorn/no-useless-fallback-in-spread": ["error"],
  "unicorn/no-useless-length-check": ["error"],
  "unicorn/no-useless-spread": ["error"],
  "unicorn/no-useless-switch-case": ["error"],
  "unicorn/no-useless-undefined": ["error"],
  "unicorn/no-zero-fractions": ["error"],
  "unicorn/numeric-separators-style": ["error"],
  "unicorn/prefer-array-find": ["error"],
  "unicorn/prefer-array-flat": ["error"],
  "unicorn/prefer-array-flat-map": ["error"],
  "unicorn/prefer-array-index-of": ["error"],
  "unicorn/prefer-array-some": ["error"],
  "unicorn/prefer-at": ["error"],
  "unicorn/prefer-class-fields": ["error"],
  "unicorn/prefer-classlist-toggle": ["error"],
  "unicorn/prefer-code-point": ["error"],
  "unicorn/prefer-date-now": ["error"],
  "unicorn/prefer-default-parameters": ["error"],
  "unicorn/prefer-dom-node-append": ["error"],
  "unicorn/prefer-dom-node-dataset": ["error"],
  "unicorn/prefer-dom-node-remove": ["error"],
  "unicorn/prefer-dom-node-text-content": ["error"],
  "unicorn/prefer-event-target": ["error"],
  "unicorn/prefer-global-this": ["error"],
  "unicorn/prefer-includes": ["error"],
  "unicorn/prefer-keyboard-event-key": ["error"],
  "unicorn/prefer-logical-operator-over-ternary": ["error"],
  "unicorn/prefer-math-min-max": ["error"],
  "unicorn/prefer-math-trunc": ["error"],
  "unicorn/prefer-modern-dom-apis": ["error"],
  "unicorn/prefer-modern-math-apis": ["error"],
  "unicorn/prefer-module": ["error"],
  "unicorn/prefer-negative-index": ["error"],
  "unicorn/prefer-node-protocol": ["error"],
  "unicorn/prefer-number-properties": [
    "error",
    {
      checkInfinity: true,
      checkNaN: true,
    },
  ],
  "unicorn/prefer-object-from-entries": ["error"],
  "unicorn/prefer-optional-catch-binding": ["error"],
  "unicorn/prefer-prototype-methods": ["error"],
  "unicorn/prefer-query-selector": ["error"],
  "unicorn/prefer-regexp-test": ["error"],
  "unicorn/prefer-response-static-json": ["error"],
  "unicorn/prefer-set-has": ["error"],
  "unicorn/prefer-set-size": ["error"],
  "unicorn/prefer-spread": ["error"],
  "unicorn/prefer-string-raw": ["error"],
  "unicorn/prefer-string-replace-all": ["error"],
  "unicorn/prefer-string-slice": ["error"],
  "unicorn/prefer-string-starts-ends-with": ["error"],
  "unicorn/prefer-string-trim-start-end": ["error"],
  "unicorn/prefer-structured-clone": ["error"],
  "unicorn/prefer-ternary": ["error"],
  "unicorn/prefer-top-level-await": ["error"],
  "unicorn/relative-url-style": ["error", "never"],
  "unicorn/require-module-attributes": ["error"],
  "unicorn/require-module-specifiers": ["error"],
  "unicorn/require-number-to-fixed-digits-argument": ["error"],
  "unicorn/switch-case-braces": ["error", "always"],
  "unicorn/text-encoding-identifier-case": ["error"],
  "unicorn/throw-new-error": ["error"],
} as const satisfies DummyRuleMap;

export const config = {
  plugins: ["unicorn"],
  rules,
} as const satisfies OxlintConfig;

export default config;
