name: PR Label

on:
  - pull_request_target

jobs:
  apply_pr_labels:
    name: Apply PR label(s)
    if: github.repository == 'arsnl/draft0'
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run labeler
        uses: actions/labeler@v6
